services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: odoo
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  odoo:
    image: odoo:17
    depends_on:
      - db
    ports:
      - "8069:8069"
    volumes:
      - odoo_data:/var/lib/odoo
      - ./odoo-addon:/mnt/extra-addons
      - ./odoo.conf:/etc/odoo/odoo.conf:ro

  fastapi:
    build: ./backend-fastapi
    depends_on:
      - redis
      - odoo
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./backend-fastapi:/app

volumes:
  pgdata:
  odoo_data:
